### ISSUE TITLE
Runtime error in TextRendering sample

### ISSUE THREAD

**Issue by Anheurystics** [openfl/lime-samples#5]
lime 4.0.2
lime-samples 4.0.1

Trying to run the TextRendering sample on Windows gives me a window that closes immediately, while on WebGL it gives an exception upon trying to access buffer.bitsPerPixel at Main.hx, line 272.

EDIT: Seems to be caused by textLayout.positions being an empty array
EDIT2: This emptiness is caused by the
`#if (lime_cffi && !macro)`
statement. (Compiling to HTML5 target)

**Comment by Anheurystics** [comment]
Any updates on this?

**Comment by jgranick** [comment]
TextRendering should now work properly on native targets, it is not currently intended for HTML5

AddingText illustrates using OpenFL for text rendering, compatible with Flash, Cairo, Canvas, DOM, WebGL, GL and GLES. This is possible in Lime as well, but `TextLayout` is a native API that wouldn't be available in other environments
